#
# /etc/pacman.conf used by mkarchiso when building the Mixosa OS airootfs.
# Based on Arch Linux's default pacman.conf with [multilib] enabled
# (required for 32-bit Wine dependencies).
#

[options]
HoldPkg     = pacman glibc
Architecture = auto

CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
